In [67]:
import pandas as pd
import numpy as np

In [68]:
df = pd.read_csv("diabetes.csv")

In [69]:
df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,2,138,62,35,0,33.6,0.127,47,1
1,0,84,82,31,125,38.2,0.233,23,0
2,0,145,0,0,0,44.2,0.630,31,1
3,0,135,68,42,250,42.3,0.365,24,1
4,1,139,62,41,480,40.7,0.536,21,0


In [70]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Pregnancies               2000 non-null   int64  
 1   Glucose                   2000 non-null   int64  
 2   BloodPressure             2000 non-null   int64  
 3   SkinThickness             2000 non-null   int64  
 4   Insulin                   2000 non-null   int64  
 5   BMI                       2000 non-null   float64
 6   DiabetesPedigreeFunction  2000 non-null   float64
 7   Age                       2000 non-null   int64  
 8   Outcome                   2000 non-null   int64  
dtypes: float64(2), int64(7)
memory usage: 140.8 KB


In [71]:
df.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [72]:
df.shape

(2000, 9)

In [73]:
df.isna().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [74]:
df

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,2,138,62,35,0,33.6,0.127,47,1
1,0,84,82,31,125,38.2,0.233,23,0
2,0,145,0,0,0,44.2,0.630,31,1
3,0,135,68,42,250,42.3,0.365,24,1
4,1,139,62,41,480,40.7,0.536,21,0
...,...,...,...,...,...,...,...,...,...
1995,2,75,64,24,55,29.7,0.370,33,0
1996,8,179,72,42,130,32.7,0.719,36,1
1997,6,85,78,0,0,31.2,0.382,42,0
1998,0,129,110,46,130,67.1,0.319,26,1


In [78]:
df['Glucose'].unique()

array([138,  84, 145, 135, 139, 173,  99, 194,  83,  89, 125,  80, 166,
       110,  81, 195, 154, 117,   0,  94,  96,  75, 180, 130, 120,  91,
       163, 122, 103, 102,  90, 111, 133, 106, 171, 159, 146,  71, 105,
       101,  88, 176, 150,  73, 187, 100,  44, 141, 114, 109,  95, 126,
       129,  79,  62, 131, 112, 113,  74, 137, 136, 107, 123, 134, 142,
       144,  92,  93, 151,  85, 155,  76, 160, 124,  78,  97, 162, 132,
       118, 170, 128, 108,  57, 147, 156, 153, 188, 152, 104, 148,  87,
       179, 143, 119, 181, 158, 196, 184, 140, 177, 197, 164, 165,  86,
       193, 191, 161, 167,  77, 115, 182, 157, 178, 116,  61, 189,  98,
       127,  82,  72, 168, 172, 175,  68, 186, 198, 121,  67, 183, 174,
       199,  56, 169, 149,  65, 190])

In [79]:
df['BloodPressure'].unique()

array([ 62,  82,   0,  68,  78,  72,  80,  65,  90,  70,  74,  64,  60,
        50,  54,  76,  84,  92, 110,  66,  56,  88,  58,  85,  86,  75,
        48,  44, 108,  55,  96, 122,  30,  52,  98, 104,  95,  46, 102,
       100,  61,  94,  24,  38, 106, 114,  40])

In [80]:
df['SkinThickness'].unique()

array([ 35,  31,   0,  42,  41,  32,  17,  28,  30,  38,  18,  15,  33,
        19,  25,  39,  26,  23,  37,  47,  24,  27,  11,  21,  34,  10,
        60,  13,  20,  22,  29,  54,  40,  51,  56,  36,  14,  50,  44,
        12,  46,  16,   7,  52,  43,  45,  48,   8,  49,  63,  99,  59,
       110])

In [81]:
df['Insulin'].unique()

array([  0, 125, 250, 480, 265,  66, 122,  76, 145, 193,  71,  79,  90,
       170, 210,  86, 105, 192, 207,  70, 240,  82,  36,  23, 300, 342,
       304, 110, 142, 128,  38, 100, 140, 270, 176,  48,  64, 228, 220,
        40, 152,  18, 135, 495,  37, 175,  51,  99,  94, 168, 225,  49,
        50,  92, 325,  63, 284, 119, 204, 155, 485,  53, 114, 285, 156,
        78, 130,  55,  58, 160, 318,  44, 190, 280,  87, 271, 129, 120,
       478,  56,  32, 744, 370,  45,  88, 194, 680, 402, 258, 375, 150,
        67,  57, 116, 278, 545,  75,  74, 182, 360, 215, 184,  42, 132,
       148, 180, 205,  96,  85, 231,  29,  68,  52, 255, 171,  73, 108,
        83,  43, 167,  54, 249, 293, 465,  89, 158,  84,  72,  59,  81,
       196, 415, 275, 115, 165, 579, 310,  61, 474, 277,  60,  14,  95,
       237, 191, 328, 326, 188, 106,  65, 166, 274,  77, 126, 330, 600,
       230, 185,  25,  41, 272, 321, 144,  15, 183,  91,  46, 440, 159,
       540, 200, 335, 387,  22, 291, 392, 178, 127, 510,  16, 11

In [82]:
df['BMI'].unique()

array([33.6, 38.2, 44.2, 42.3, 40.7, 46.5, 25.6, 26.1, 36.8, 33.5, 32.8,
       28.9,  0. , 26.6, 26. , 30.1, 25.1, 29.3, 25.2, 37.2, 39. , 33.3,
       37.3, 36.5, 28.6, 30.4, 25. , 29.7, 22.1, 24.2, 27.3, 31.6, 27.6,
       24. , 33.2, 32.9, 37.1, 34. , 40.2, 22.7, 45.4, 27.4, 42. , 28. ,
       39.1, 19.4, 24.4, 33.7, 34.7, 23. , 37.7, 46.8, 40.5, 41.5, 25.4,
       29. , 32.5, 42.7, 19.6, 43.4, 35.1, 32. , 24.7, 32.6, 43.2, 22.4,
       24.6, 48.8, 32.4, 36.6, 38.5, 26.5, 19.1, 46.7, 23.8, 33.9, 20.4,
       28.7, 49.7, 22.5, 39.6, 29.5, 34.3, 37.4, 31.2, 30.5, 28.2, 23.2,
       53.2, 34.2, 26.8, 55. , 42.9, 34.5, 27.9, 38.3, 21.1, 33.8, 30.8,
       36.9, 39.5, 21.9, 40.6, 47.9, 50. , 40.9, 29.9, 29.6, 31.9, 28.4,
       35.4, 43.5, 32.7, 67.1, 45. , 34.9, 27.7, 35.9, 22.6, 33.1, 52.3,
       39.4, 24.3, 22.9, 34.8, 30.9, 31. , 40.1, 23.9, 37.5, 35.5, 42.8,
       42.6, 41.8, 35.8, 30. , 37.8, 34.6, 28.8, 23.6, 35.7, 36.7, 45.2,
       44. , 46.2, 35. , 43.6, 44.1, 18.4, 29.2, 27

In [83]:
df['Age'].unique()

array([47, 23, 31, 24, 21, 58, 28, 67, 42, 33, 45, 22, 66, 30, 25, 55, 39,
       41, 40, 38, 35, 64, 46, 27, 56, 26, 37, 48, 54, 29, 44, 36, 32, 43,
       34, 60, 61, 69, 62, 65, 57, 52, 51, 49, 63, 59, 72, 81, 50, 53, 70,
       68])

In [84]:
df['DiabetesPedigreeFunction'].unique()

array([0.127, 0.233, 0.63 , 0.365, 0.536, 1.159, 0.294, 0.551, 0.629,
       0.292, 0.145, 1.144, 0.174, 0.304, 0.547, 0.163, 0.839, 0.313,
       0.267, 0.727, 0.738, 0.238, 0.263, 0.314, 0.692, 0.968, 0.409,
       0.297, 0.207, 0.2  , 0.525, 0.154, 0.268, 0.512, 0.966, 0.42 ,
       0.665, 0.503, 1.39 , 0.271, 0.696, 0.235, 0.721, 1.893, 0.564,
       0.586, 0.344, 0.305, 0.491, 0.526, 0.342, 0.467, 0.718, 0.248,
       0.254, 0.962, 1.781, 0.173, 0.27 , 0.587, 0.699, 0.258, 0.203,
       0.855, 0.845, 0.334, 0.189, 0.867, 0.411, 0.583, 0.231, 0.396,
       0.14 , 0.391, 0.37 , 0.307, 0.102, 0.767, 0.237, 0.227, 0.698,
       0.178, 0.324, 0.153, 0.165, 0.443, 0.261, 0.277, 0.761, 0.255,
       0.13 , 0.323, 0.356, 0.325, 1.222, 0.179, 0.262, 0.283, 0.93 ,
       0.801, 0.287, 0.336, 0.247, 0.199, 0.543, 0.192, 0.588, 0.539,
       0.22 , 0.654, 0.223, 0.759, 0.26 , 0.404, 0.186, 0.278, 0.496,
       0.452, 0.403, 0.741, 0.361, 1.114, 0.457, 0.647, 0.088, 0.597,
       0.532, 0.703,

In [85]:
columns_with_zero= ['Glucose', 'BloodPressure','SkinThickness', 'Insulin', 'BMI', 'DiabetesPedigreeFunction', 'Age']

In [86]:
for col in columns_with_zero:
    df[col]= df[col].replace(0, np.nan)

In [87]:
df

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,2,138.0,62.0,35.0,NaN,33.6,0.127,47,1
1,0,84.0,82.0,31.0,125.0,38.2,0.233,23,0
2,0,145.0,NaN,NaN,NaN,44.2,0.630,31,1
3,0,135.0,68.0,42.0,250.0,42.3,0.365,24,1
4,1,139.0,62.0,41.0,480.0,40.7,0.536,21,0
...,...,...,...,...,...,...,...,...,...
1995,2,75.0,64.0,24.0,55.0,29.7,0.370,33,0
1996,8,179.0,72.0,42.0,130.0,32.7,0.719,36,1
1997,6,85.0,78.0,NaN,NaN,31.2,0.382,42,0
1998,0,129.0,110.0,46.0,130.0,67.1,0.319,26,1


In [88]:
df.isna().sum()

Pregnancies                   0
Glucose                      13
BloodPressure                90
SkinThickness               573
Insulin                     956
BMI                          28
DiabetesPedigreeFunction      0
Age                           0
Outcome                       0
dtype: int64

In [89]:
for col in columns_with_zero:
    df[col] = df[col].fillna(df[col].median())

In [90]:
df.isna().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [91]:
from sklearn.model_selection import train_test_split

In [92]:
X= df.drop('Outcome', axis= 1)
y= df['Outcome']

In [93]:
X

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
0,2,138.0,62.0,35.0,126.0,33.6,0.127,47
1,0,84.0,82.0,31.0,125.0,38.2,0.233,23
2,0,145.0,72.0,29.0,126.0,44.2,0.630,31
3,0,135.0,68.0,42.0,250.0,42.3,0.365,24
4,1,139.0,62.0,41.0,480.0,40.7,0.536,21
...,...,...,...,...,...,...,...,...
1995,2,75.0,64.0,24.0,55.0,29.7,0.370,33
1996,8,179.0,72.0,42.0,130.0,32.7,0.719,36
1997,6,85.0,78.0,29.0,126.0,31.2,0.382,42
1998,0,129.0,110.0,46.0,130.0,67.1,0.319,26


In [94]:
y

0       1
1       0
2       1
3       1
4       0
       ..
1995    0
1996    1
1997    0
1998    1
1999    0
Name: Outcome, Length: 2000, dtype: int64

In [97]:
print(X.columns)

Index(['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI', 'DiabetesPedigreeFunction', 'Age'],
      dtype='str')


In [98]:
 X_train, X_test, y_train, y_test = train_test_split(X,y, test_size= 0.2, random_state= 20)

In [99]:
print(X.shape, X_train.shape, X_test.shape)

(2000, 8) (1600, 8) (400, 8)


In [100]:
print(y.shape, y_train.shape, y_test.shape)

(2000,) (1600,) (400,)


In [101]:
from sklearn.linear_model import LogisticRegression

In [102]:
model = LogisticRegression()

In [103]:
model.fit(X_train, y_train)

C:\Users\mohdr\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\linear_model\_logistic.py:599: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


,"penalty penalty: {'l1', 'l2', 'elasticnet', None}, default='l2'Specify the norm of the penalty:- `None`: no penalty is added;- `'l2'`: add an L2 penalty term and it is the default choice;- `'l1'`: add an L1 penalty term;- `'elasticnet'`: both L1 and L2 penalty terms are added... warning:: Some penalties may not work with some solvers. See the parameter `solver` below, to know the compatibility between the penalty and solver... versionadded:: 0.19 l1 penalty with SAGA solver (allowing 'multinomial' + L1).. deprecated:: 1.8 `penalty` was deprecated in version 1.8 and will be removed in 1.10. Use `l1_ratio` and `C` instead. `l1_ratio=0` for `penalty='l2'`, `l1_ratio=1` for `penalty='l1'`, `l1_ratio` set to any float between 0 and 1 for `penalty='elasticnet'`, and `C=np.inf` for `penalty=None`.",'deprecated'
,"C C: float, default=1.0Inverse of regularization strength; must be a positive float.Like in support vector machines, smaller values specify strongerregularization. `C=np.inf` results in unpenalized logistic regression.For a visual example on the effect of tuning the `C` parameterwith an L1 penalty, see::ref:`sphx_glr_auto_examples_linear_model_plot_logistic_path.py`.",1.0
,"l1_ratio l1_ratio: float, default=0.0The Elastic-Net mixing parameter, with `0 <= l1_ratio <= 1`. Setting`l1_ratio=1` gives a pure L1-penalty, setting `l1_ratio=0` a pure L2-penalty.Any value between 0 and 1 gives an Elastic-Net penalty of the form`l1_ratio * L1 + (1 - l1_ratio) * L2`... warning:: Certain values of `l1_ratio`, i.e. some penalties, may not work with some solvers. See the parameter `solver` below, to know the compatibility between the penalty and solver... versionchanged:: 1.8 Default value changed from None to 0.0... deprecated:: 1.8 `None` is deprecated and will be removed in version 1.10. Always use `l1_ratio` to specify the penalty type.",0.0
,"dual dual: bool, default=FalseDual (constrained) or primal (regularized, see also:ref:`this equation <regularized-logistic-loss>`) formulation. Dual formulationis only implemented for l2 penalty with liblinear solver. Prefer `dual=False`when n_samples > n_features.",False
,"tol tol: float, default=1e-4Tolerance for stopping criteria.",0.0001
,"fit_intercept fit_intercept: bool, default=TrueSpecifies if a constant (a.k.a. bias or intercept) should beadded to the decision function.",True
,"intercept_scaling intercept_scaling: float, default=1Useful only when the solver `liblinear` is usedand `self.fit_intercept` is set to `True`. In this case, `x` becomes`[x, self.intercept_scaling]`,i.e. a ""synthetic"" feature with constant value equal to`intercept_scaling` is appended to the instance vector.The intercept becomes``intercept_scaling * synthetic_feature_weight``... note:: The synthetic feature weight is subject to L1 or L2 regularization as all other features. To lessen the effect of regularization on synthetic feature weight (and therefore on the intercept) `intercept_scaling` has to be increased.",1
,"class_weight class_weight: dict or 'balanced', default=NoneWeights associated with classes in the form ``{class_label: weight}``.If not given, all classes are supposed to have weight one.The ""balanced"" mode uses the values of y to automatically adjustweights inversely proportional to class frequencies in the input dataas ``n_samples / (n_classes * np.bincount(y))``.Note that these weights will be multiplied with sample_weight (passedthrough the fit method) if sample_weight is specified... versionadded:: 0.17 *class_weight='balanced'*",None
,"random_state random_state: int, RandomState instance, default=NoneUsed when ``solver`` == 'sag', 'saga' or 'liblinear' to shuffle thedata. See :term:`Glossary <random_state>` for details.",None
,"solver solver: {'lbfgs', 'liblinear', 'newton-cg', 'newton-cholesky', 'sag', 'saga'}, default='lbfgs'Algorithm to use in the optimization problem. Default is 'lbfgs'.To choose a solver, you might want to consider the following aspects:- 'lbfgs' is a good default sol

In [104]:
from sklearn.metrics import accuracy_score

In [105]:
y_pred = model.predict(X_test)

In [106]:
acc= accuracy_score(y_test, y_pred)

In [107]:
acc

0.7475

In [109]:
model.predict([[4,132.0,63.0,31.0,122.0,32.6,0.127,57]])

C:\Users\mohdr\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2827: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


array([0])

In [110]:
import pickle 

In [111]:
pickle.dump(model, open('diabetes_pred.pkl', 'wb'))